# ruff.toml

target-version = "py310"
line-length = 88

fix = false

[lint]
select = [
    "E",
    "F",
    "W",
    "I",
    "N",
    "UP",
    "B",
    "A",
    "C4",
    "SIM",
]

ignore = [
    "E501",
    "B008",
]


exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "weights",
    "Predictions",
]

[lint.isort]
known-first-party = ["models", "losses", "dataloader"]
combine-as-imports = true

[lint.pep8-naming]
classmethod-decorators = ["classmethod"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"